name: trousseau

k8sDistro: default
namespace: kube-system 

kmsplugin:
  vault: 
    name: vault-kms-provider 
    serviceaccount:
      name: vault-auth 
    trousseau:
      image: 
        registry: ghcr.io
        repository: ondat/trousseau
        tag: v1.1.0
        pullPolicy: IfNotPresent
    vaultagent:
      image: 
        repository: vault
        tag: 1.8.6
        pullPolicy: IfNotPresent

securityContext: 
  allowPrivilegeEscalation: false 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsUser: 0

resources:
  requests:
    cpu: 300m
    memory: 64Mi
  limits: 
    cpu: 300m 
    memory: 256Mi 

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/etcd
    operator: Exists
    effect: NoExecute

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
