apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.kmsplugin.name }}
  namespace: {{ .Values.kmsplugin.namespace }}
  labels:
    tier: control-plane 
    app: {{ .Values.kmsplugin.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.kmsplugin.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.kmsplugin.name }}
    spec:
      serviceAccountName: {{ include "trousseau.serviceAccountName" . }}
      priorityClassName: system-cluster-critical 
      hostNetwork: true 
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: vault-agent
          image: "{{ .Values.vaultagent.image.repository }}:{{ .Values.vaultagent.image.tag }}"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
